import Navbar from "@/app/_components/navbar.tsx"
import styles from '@/styles/layout.module.scss';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  )
}
